import React from 'react';
import { Card } from '../common/Card';
import { Badge } from '../common/Badge';
import { EmptyState } from '../common/EmptyState';
import { FileCheck, Download, ExternalLink } from 'lucide-react';
import { Link } from 'react-router-dom';

export const RecentReports = ({ reports = [] }) => {
  return (
    <Card
      title="Recent Analyst Reports"
      subtitle="Structured PDF/Markdown exports generated by Report Agent"
      headerAction={
        <Link to="/reports" className="text-xs font-semibold text-emerald-400 hover:text-emerald-300">
          View All Reports →
        </Link>
      }
    >
      {reports.length === 0 ? (
        <EmptyState
          icon={FileCheck}
          title="No analyst reports yet"
          description="Generated reports include an executive summary, extracted metrics, red flags and peer ratios — each cited to its source filing."
          action={
            <Link
              to="/reports"
              className="inline-flex items-center gap-1.5 h-9 px-3.5 rounded-lg text-xs font-semibold text-white bg-brand-600 hover:bg-brand-500 transition-colors"
            >
              Go to reports <ExternalLink className="w-3.5 h-3.5" />
            </Link>
          }
        />
      ) : (
        <div className="space-y-3">
          {reports.map((rep) => (
            <div
              key={rep.id}
              className="p-3.5 rounded-lg glass-inset flex items-center justify-between hover:border-slate-600 transition-colors"
            >
              <div className="flex items-center gap-3 min-w-0">
                <div className="w-8 h-8 rounded-lg bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400 shrink-0">
                  <FileCheck className="w-4 h-4" />
                </div>
                <div className="min-w-0">
                  <h4 className="font-semibold text-slate-200 text-xs truncate">
                    {rep.title}
                  </h4>
                  <p className="text-[11px] text-slate-400 truncate mt-0.5">
                    {rep.company_name} • Grounded in Source Docs
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-2 shrink-0">
                <Badge variant="emerald">{rep.status}</Badge>
                <Link
                  to="/reports"
                  className="p-1.5 text-slate-400 hover:text-emerald-400 hover:bg-emerald-500/10 rounded-lg transition-colors"
                  title="Open Report"
                >
                  <ExternalLink className="w-4 h-4" />
                </Link>
              </div>
            </div>
          ))}
        </div>
      )}
    </Card>
  );
};
