from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class CompanyMetrics(BaseModel):
    """
    Financial metrics for a single company.
    The Comparison Agent receives these values and
    uses them for scoring and ranking.
    """

    company_name: str = Field(..., description="Name of the company")

    metrics: Dict[str, Optional[float]] = Field(
        ...,
        description="Financial metrics for the company"
    )


class ComparisonRequest(BaseModel):
    """
    Input received by the Comparison Agent.
    """

    workspace_id: Optional[str] = None

    companies: List[CompanyMetrics] = Field(
        ...,
        min_length=2,
        description="At least two companies are required for comparison"
    )

    criteria: Optional[List[str]] = Field(
        default=None,
        description="Metrics to use for comparison"
    )

    weights: Optional[Dict[str, float]] = Field(
        default=None,
        description="Optional weights for comparison metrics"
    )


class MetricComparison(BaseModel):
    """
    Result of comparing one metric across companies.
    """

    metric: str

    values: Dict[str, Optional[float]]

    leader: Optional[str] = None

    higher_is_better: bool


class CompanyRanking(BaseModel):
    """
    Final score and rank for a company.
    """

    rank: int

    company_name: str

    overall_score: float

    metric_scores: Dict[str, float]


class ComparisonResponse(BaseModel):
    """
    Final output generated by the Comparison Agent.
    This will later be sent to the Report Agent and frontend.
    """

    workspace_id: Optional[str] = None

    rankings: List[CompanyRanking]

    metric_comparisons: List[MetricComparison]

    summary: str