# MARK: Imports
import uuid
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException

from app.schemas import (
    ChatQueryRequest,
    ChatQueryResponse,
    ChatHistoryResponse,
    ChatMessageResponse,
    Citation
)

from app.core.database import get_db
from app.core.security import get_current_user_token
from app.agents.crew_runner import FinancialCrewRunner
from app.schemas import ChatQueryRequest, ChatQueryResponse, ChatHistoryResponse, ChatMessageResponse, Citation
from app.core.database import get_db
from app.core.security import get_current_user_token

# MARK: Router Setup
router = APIRouter(prefix="/chat", tags=["Conversational Research Interface"])

# MARK: Endpoints
@router.post("/query", response_model=ChatQueryResponse)
async def query_chat(query_in: ChatQueryRequest, token_data: dict = Depends(get_current_user_token)):
    user_id = token_data.get("sub")
    db = get_db()
    chat_col = db["chat_history"]
    
    msg_id = f"msg_{uuid.uuid4().hex[:12]}"
    now_str = datetime.now(timezone.utc).isoformat()
    
    await chat_col.insert_one({
        "_id": f"usr_msg_{uuid.uuid4().hex[:8]}",
        "workspace_id": query_in.workspace_id,
        "user_id": user_id,
        "role": "user",
        "content": query_in.query,
        "timestamp": now_str
    })
    
        # ------------------------------------------------------------
    # Run the actual Research Agent chatbot pipeline
    # ------------------------------------------------------------

    # Verify that the workspace belongs to the logged-in user
    ws_col = db["workspaces"]
    workspace = await ws_col.find_one({
        "_id": query_in.workspace_id,
        "user_id": user_id
    })

    if not workspace:
        raise HTTPException(
            status_code=404,
            detail="Workspace not found"
        )

    # Get documents belonging to this workspace
    docs_col = db["documents"]

    documents = await docs_col.find({
        "workspace_id": query_in.workspace_id,
        "user_id": user_id,
        "status": "INDEXED"
    }).to_list(length=None)

    if not documents:
        raise HTTPException(
            status_code=400,
            detail="No indexed documents are available in this workspace."
        )

    # Use the first indexed document for the research query.
    # Multi-document support can be added later.
    # Select an indexed document that actually has processed chunks
    document = None

    for doc in documents:
        if doc.get("chunks_count", 0) > 0:
            document = doc
            break

    if not document:
        raise HTTPException(
            status_code=400,
            detail="No indexed document with processed chunks is available in this workspace."
        )

    document_id = document["_id"]
    company_name = (
        query_in.company_name
        or document.get("company_name")
        or "Unknown Company"
    )

    # Retrieve processed chunks generated by the Document Agent
    chunks_col = db["parsed_chunks"]

    chunks_cursor = chunks_col.find(
        {"document_id": document_id}
    ).sort("page_number", 1)

    chunks = await chunks_cursor.to_list(length=None)

    if not chunks:
        raise HTTPException(
            status_code=400,
            detail="The selected document has not produced any processed chunks."
        )

    # Build the document context for the Research pipeline
    document_parts = []

    for chunk in chunks:
        page_number = chunk.get(
            "page_number",
            chunk.get("page_start", "Unknown")
        )

        section = chunk.get(
            "section_type",
            "General"
        )

        text = chunk.get("text", "").strip()

        if text:
            document_parts.append(
                f"[Page {page_number} | Section: {section}]\n{text}"
            )

    document_text = "\n\n".join(document_parts)

    if not document_text:
        raise HTTPException(
            status_code=400,
            detail="No usable text was found in the indexed document."
        )

    # Run:
    # Extraction → Red Flag → Comparison → Research
    answer_text = await FinancialCrewRunner.run_research(
        document_id=document_id,
        document_text=document_text,
        query=query_in.query,
        company_name=company_name
    )

    # The Research Agent currently returns textual analysis.
    reasoning = [
        "Document Agent provided the indexed financial document context.",
        "Extraction Agent analyzed the financial metrics.",
        "Red Flag Agent analyzed potential financial risks.",
        "Comparison Agent evaluated financial performance.",
        "Research Agent synthesized the findings to answer the user query."
    ]

    # Citations will be populated from structured source metadata
    # once the Research Agent returns source-level citations.
    citations = []

    assistant_msg = ChatMessageResponse(
        id=msg_id,
        workspace_id=query_in.workspace_id,
        role="assistant",
        content=answer_text,
        reasoning_steps=reasoning,
        citations=citations,
        timestamp=now_str
    )
    
    await chat_col.insert_one({
        "_id": msg_id,
        "workspace_id": query_in.workspace_id,
        "user_id": user_id,
        "role": "assistant",
        "content": answer_text,
        "reasoning_steps": [r for r in reasoning],
        "citations": [c.model_dump() for c in citations],
        "timestamp": now_str
    })
    
    return ChatQueryResponse(message=assistant_msg, agent_status="Research Agent citation verified")

@router.get("/history/{workspace_id}", response_model=ChatHistoryResponse)
async def get_chat_history(workspace_id: str, token_data: dict = Depends(get_current_user_token)):
    user_id = token_data.get("sub")
    db = get_db()
    chat_col = db["chat_history"]
    
    cursor = chat_col.find({"workspace_id": workspace_id, "user_id": user_id}).sort("timestamp", 1)
    items = []
    async for doc in cursor:
        citations_list = []
        if doc.get("citations"):
            for c in doc["citations"]:
                citations_list.append(Citation(**c))
        items.append(ChatMessageResponse(
            id=doc["_id"],
            workspace_id=doc["workspace_id"],
            role=doc["role"],
            content=doc["content"],
            reasoning_steps=doc.get("reasoning_steps"),
            citations=citations_list if citations_list else None,
            timestamp=doc["timestamp"]
        ))
    return ChatHistoryResponse(messages=items)
